# Netlify configuration for IntraDay Trading Dashboard - Static Deployment

[build]
  # Command to build the static application
  command = "./build-static.sh"
  
  # Directory containing the built files (frontend only for static hosting)
  publish = "dist"
  
  # Environment variables for build
  [build.environment]
    NODE_ENV = "production"
    NODE_VERSION = "20"

# Single Page Application redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"